-- The approvals queue claims to be newest-first, but two approvals created in the same millisecond
-- share a requested_at, and the primary key is a random UUID, so the tie was settled by whatever
-- order the database happened to return. ApprovalQueueOrderTest failed intermittently for exactly
-- that reason: the queue a human reads was only usually in the right order.
--
-- An identity column gives insert order, which always increases.
ALTER TABLE approvals ADD COLUMN sequence BIGINT GENERATED BY DEFAULT AS IDENTITY;
