import { ArrowUpRight, Plus, Upload, Activity, Coins, FileCheck2, ShieldCheck, Users, ArrowLeftRight } from 'lucide-react'
import AgentCommandBox from '../components/AgentCommandBox'
import accounts from '../mocks/accounts.json'; import payments from '../mocks/payments.json'; import tokens from '../mocks/tokens.json'; import audit from '../mocks/audit.json'; import approvals from '../mocks/approvals.json'
type Kind = 'accounts'|'payments'|'tokens'|'audit'|'policies'|'approvals'
const config: Record<Kind, {title:string; subtitle:string; agent:string; placeholder:string; icon:any; action?:string; secondary?:string; empty:string}> = {
 accounts: { title:'Accounts & Wallets', subtitle:'Create, manage, and inspect Hedera accounts.', agent:'AccountAgent', placeholder:'Ask Account Agent…', icon:Users, action:'Create Account', empty:'No accounts yet.' },
 payments: { title:'Payments & Treasury', subtitle:'Move value with clear controls and traceability.', agent:'PaymentAgent', placeholder:'Ask Payment Agent…', icon:ArrowLeftRight, action:'New Payment', secondary:'Bulk Payment', empty:'No payments yet.' },
 tokens: { title:'Tokens & Assets', subtitle:'A home for your HTS assets and token operations.', agent:'TokenAgent', placeholder:'Ask Token Agent…', icon:Coins, action:'Create Token', empty:'No tokens yet.' },
 audit: { title:'Audit & Monitoring', subtitle:'See what agents did and verify every operation.', agent:'MonitoringAgent', placeholder:'Ask Monitoring Agent…', icon:Activity, empty:'No audit events yet.' },
 policies: { title:'Policies & Approvals', subtitle:'Define guardrails for conditional execution.', agent:'PolicyAgent', placeholder:'Ask Policy Agent…', icon:ShieldCheck, action:'Create Policy', empty:'No policies configured yet.' },
 approvals: { title:'Approvals', subtitle:'Review work waiting for a human decision.', agent:'PolicyAgent', placeholder:'Ask Policy Agent about approvals…', icon:FileCheck2, empty:'No approvals waiting.' }
}
export default function FeaturePage({ kind }: { kind: Kind }) { const c=config[kind]; const Icon=c.icon; const data=kind==='accounts'?accounts:kind==='payments'?payments:kind==='tokens'?tokens:kind==='audit'?audit:approvals; return <><div className="page-heading"><div><p className="eyebrow">MODULE / {kind.toUpperCase()}</p><h1>{c.title}</h1><p className="subtitle">{c.subtitle}</p></div><div className="page-actions">{c.secondary && <button className="button secondary"><Upload size={15}/>{c.secondary}</button>}{c.action && <button className="button primary"><Plus size={15}/>{c.action}</button>}</div></div><AgentCommandBox agentName={c.agent} placeholder={c.placeholder}/><div className="section-label"><span>MOCK DATA</span><span className="line"/><span className="mock-pill">PLACEHOLDER</span></div><div className="data-panel">{data.length ? <div className="data-list">{data.map((item:any) => <div className="data-row" key={item.id}><div className="data-leading"><div className="row-icon"><Icon size={16}/></div><div><b>{item.name || item.id}</b><span>{item.hederaAccountId || item.destination || item.agent || item.taskId || item.symbol || 'Starter record'}</span></div></div><div className="row-meta"><span className="status-badge">{item.status}</span><ArrowUpRight size={15}/></div></div>)}</div> : <div className="empty-state"><div className="empty-icon"><Icon size={20}/></div><p>{c.empty}</p><span>Connect this module's backend when you start feature work.</span></div>}</div></> }
