import { FormEvent, useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { changePassword, deleteAccount, getAuthUser, getCurrentAccount, logout, updateProfile } from '../api/client'

export default function SettingsPage() {
  const navigate = useNavigate(); const user = getAuthUser<any>(); const [account, setAccount] = useState<any>(user?.account ?? null)
  const [email, setEmail] = useState(user?.email ?? ''); const [displayName, setDisplayName] = useState(user?.displayName ?? '')
  const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  useEffect(() => { getCurrentAccount().then(setAccount).catch(() => undefined) }, [])
  async function profile(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); try { await updateProfile(email, displayName); setMessage('Profile updated successfully.') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update profile') } }
  async function password(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); try { await changePassword(currentPassword, newPassword); setCurrentPassword(''); setNewPassword(''); setMessage('Password changed successfully.') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to change password') } }
  async function signOut() { await logout(); navigate('/login', { replace: true }) }
  async function remove() { if (!window.confirm('Delete your account and wallet association permanently?')) return; await deleteAccount(); navigate('/login', { replace: true }) }
  return <><div className="page-heading"><div><p className="eyebrow">ACCOUNT / SETTINGS</p><h1>Account settings</h1><p className="subtitle">Manage your profile, password, session, and wallet association.</p></div></div>{message && <div className="auth-success">{message}</div>}{error && <div className="auth-error settings-message">{error}</div>}<div className="settings-grid"><section className="data-panel settings-card"><h2>Profile</h2><p>Role: <b>{user?.role}</b></p><form onSubmit={profile}><label>Email<input type="email" required value={email} onChange={e => setEmail(e.target.value)}/></label><label>Display name<input required value={displayName} onChange={e => setDisplayName(e.target.value)}/></label><button className="button primary">Save profile</button></form></section><section className="data-panel settings-card"><h2>Security</h2><p>Change the password used to access this workspace.</p><form onSubmit={password}><label>Current password<input type="password" required value={currentPassword} onChange={e => setCurrentPassword(e.target.value)}/></label><label>New password<input type="password" required minLength={8} value={newPassword} onChange={e => setNewPassword(e.target.value)}/></label><button className="button primary">Change password</button></form></section><section className="data-panel settings-card wallet-card"><h2>Wallet</h2><p>Your Hedera wallet is assigned when the account is created.</p><div className="wallet-id-label">HEDERA ACCOUNT ID</div><code className="wallet-id">{account?.hederaAccountId ?? 'Loading wallet…'}</code><div className="wallet-meta">Status: <b>{account?.status ?? '—'}</b> · Balance: <b>{account?.balance ?? '—'}</b> HBAR</div><button className="button secondary" onClick={signOut}>Log out</button><button className="danger-button" onClick={remove}>Delete account</button></section></div></>
}
